USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/hardkernel/odroidc/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := odroidc
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a9
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := odroidc

BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048

BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00800000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00800000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x40000000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0xc0000000
BOARD_FLASH_BLOCK_SIZE := 2048

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_RECOVERY_INITRC := device/hardkernel/odroidc/recovery/init.odroidc.rc
TARGET_RECOVERY_FSTAB := device/hardkernel/odroidc/recovery/recovery.fstab
#BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_15x24.h\"

TARGET_PREBUILT_KERNEL := device/hardkernel/odroidc/prebuilt/kernel

BOARD_MKBOOTIMG_ARGS := --second device/hardkernel/odroidc/prebuilt/meson8b_odroidc.dtb

BOARD_TVMODE_ALL_SCALE := true
TARGET_NO_RADIOIMAGE := true
TARGET_SIMULATOR := false

# TARGET_ENABLE_SCALE_FUNCTION := true
TARGET_HAS_HDMIONLY_FUNCTION := true

USE_OPENGL_RENDERER := true

# GPU
USING_MALI450:=true
USING_ION:=true

# SENSOR
BOARD_SENSOR_AMLOGIC:=true
BOARD_SENSOR_KIONIX_61G:=false
#PRODUCT_EXTRA_RECOVERY_KEYS := ../common/releasekey.x509.pem

DEVICE_RESOLUTION := 1280x720
TARGET_SCREEN_WIDTH := 1280
TARGET_SCREEN_HEIGHT := 720
BOARD_HAS_NO_SELECT_BUTTON := true

BOARD_HAS_NO_MISC_PARTITION := true
#BOARD_HAS_DATADATA := false
#BOARD_HAS_SDCARD_INTERNAL := true
#BOARD_SDCARD_DEVICE_PRIMARY := /dev/block/mmcblk0p1
#BOARD_SDCARD_DEVICE_INTERNAL := /dev/block/mmcblk0p1

